services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
    ports:
      - ${TEST_DB_PORT}:${TEST_DB_PORT}
    command:
      - "postgres"
      - "-c"
      - "port=${TEST_DB_PORT}"
    volumes:
      - ./migrations/test-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${TEST_POSTGRES_USER} -d ${TEST_DB_NAME}'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:

volumes:
  postgres:
